# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f513b8d2015a27b77b8cd08e39de6a66c558306094aa2767f1b5c6f0fcce4d2550943b121692b43db0646f61a1450e3b629e6d5025cbf69cb99d3f8f6816aeff

test:
  secret_key_base: ac47b2e7975f44518f0c988d75c494c48d3f9603e24cc2b0ba076bf7c91df6a02ca9530ba81de70f120c5f83e98166c22e876e4862093a92bbee73ccc17ec62e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
